
# port
server:
  port: 8765

spring:
  # name
  application:
    name: "api-gateway"

  # enable api gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

# eureka-client-registration
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
