
# port
server:
  port: 8765

spring:
  # name
  application:
    name: "api-gateway"

# eureka-client-registration
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
